# Generated by Django 4.1.13 on 2024-04-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('property_type', models.CharField(max_length=25)),
                ('total_bedrooms', models.IntegerField()),
                ('total_bathrooms', models.IntegerField()),
                ('summary', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
